version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./documents:/app/documents
    environment:
      - DATABASE_URL=sqlite:///./documents.db
    restart: unless-stopped 